# Generated by Django 5.2.17 on 2026-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_url', models.URLField(help_text="Root URL of the external system's API, e.g. https://api.example.com")),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth2 (Authorization Code)'), ('api_key', 'API Key / Bearer Token'), ('basic', 'Basic Auth'), ('none', 'No auth')], default='api_key', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='OAuth2: client_id, client_secret, authorize_url, token_url, scope. API key: header_name (default Authorization), prefix (default Bearer). Basic: no config needed.')),
                ('secrets_encrypted', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
