# Generated by Django 5.2.17 on 2026-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text="OAuth2: client_id, client_secret, authorize_url, token_url, scope. Bearer: header_name (default Authorization), prefix (default Bearer). JWT: claims (dict, 'exp' filled in automatically), ttl_seconds (default 3600), algorithm (default HS256). Basic: no config needed."),
        ),
        migrations.AlterField(
            model_name='connection',
            name='auth_type',
            field=models.CharField(choices=[('oauth2', 'OAuth2 (Authorization Code)'), ('basic', 'Basic Auth'), ('jwt', 'JWT (self-signed)'), ('bearer', 'Bearer Token'), ('none', 'No auth')], default='bearer', max_length=20),
        ),
    ]
