# Generated by Django 5.2.17 on 2026-09-07 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_auth_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=180, help_text="How often to proactively refresh. Keep it comfortably under both the access token's lifetime and the refresh token's own lifetime (e.g. Tiny ERP: access token lasts 4h, refresh token 1 day — every 180 min refreshes well inside both).")),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('success', 'success'), ('failed', 'failed')], max_length=10)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_refresh_job', to='connections.connection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
