# Generated by Django 5.2.17 on 2026-09-07 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_tokenrefreshjob'),
        ('jobs', '0004_migrationrun_rate_limit_per_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=1000)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True, help_text='Set instead of status_code/response_* when the request itself failed (timeout, DNS, connection refused, ...).')),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to='connections.connection')),
                ('run', models.ForeignKey(blank=True, help_text="Set when this call happened inside a migration run's read/write step.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to='jobs.migrationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
