# Generated by Django 5.2.17 on 2026-09-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_apicalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict, help_text='{"header-name": "value", ...} — only applied when use_custom_headers is on.'),
        ),
        migrations.AddField(
            model_name='connection',
            name='custom_params',
            field=models.JSONField(blank=True, default=dict, help_text='{"param-name": "value", ...} — only applied when use_custom_params is on.'),
        ),
        migrations.AddField(
            model_name='connection',
            name='use_custom_headers',
            field=models.BooleanField(default=False, help_text="When on, custom_headers is sent with every request on top of whatever auth_type already adds (Bearer/JWT/etc.) — off just leaves custom_headers unused, so values already entered aren't lost by unchecking this."),
        ),
        migrations.AddField(
            model_name='connection',
            name='use_custom_params',
            field=models.BooleanField(default=False, help_text="When on, custom_params is added to every request's query string on top of whatever the call itself already passes — off just leaves custom_params unused."),
        ),
    ]
