# Generated by Django 5.2.17 on 2026-09-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_connection_custom_headers_connection_custom_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='rate_limit_per_second',
            field=models.FloatField(blank=True, help_text='Max requests/second the app will send to this connection. Set this to whatever the external API actually allows to stop hitting HTTP 429 — every migration run touching this connection is throttled to it automatically unless the run sets its own, stricter rate_limit_per_second. Leave blank for no limit.', null=True),
        ),
    ]
