# Generated by Django 5.2.17 on 2026-09-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_connection_rate_limit_per_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text='OAuth2: client_id, client_secret, authorize_url, token_url, scope, plus optionally client_auth (\'basic\' to send the credentials as an HTTP Basic header) and extra_headers ({"enable-jwt": "1"}, sent on token calls and API requests — see connections/oauth.py). Bearer: header_name (default Authorization), prefix (default Bearer). JWT: claims (dict, \'exp\' filled in automatically), ttl_seconds (default 3600), algorithm (default HS256). Basic: no config needed.'),
        ),
    ]
