# Generated by Django 5.2.17 on 2026-09-06 19:16

import django.db.models.deletion
import integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_alter_connection_auth_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ECOMMERCE', 'E-commerce'), ('ERP', 'ERP'), ('ACCOUNTING', 'Accounting'), ('NOTIFICATIONS', 'Notifications'), ('CRM', 'CRM'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('icon', models.CharField(default='bi-puzzle', help_text="A Bootstrap Icons class, e.g. 'bi-shop'.", max_length=50)),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth2 (Authorization Code)'), ('basic', 'Basic Auth'), ('jwt', 'JWT (self-signed)'), ('bearer', 'Bearer Token'), ('none', 'No auth')], default='bearer', help_text='Authentication scheme this app expects — determines which fields the install form asks for.', max_length=20)),
                ('default_base_url', models.URLField(blank=True, help_text='Pre-filled base URL for installs of this integration.')),
                ('oauth_authorize_url', models.URLField(blank=True, help_text="Provider's /authorize endpoint.")),
                ('oauth_token_url', models.URLField(blank=True, help_text="Provider's /token endpoint.")),
                ('oauth_client_id', models.CharField(blank=True, max_length=255)),
                ('oauth_client_secret', models.CharField(blank=True, max_length=255)),
                ('oauth_scope', models.CharField(blank=True, max_length=255)),
                ('setup_url', models.URLField(blank=True, help_text='External docs/setup link shown on the install form, if any.')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstalledIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_install', to='connections.connection')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthPendingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default=integrations.models.generate_oauth_state, editable=False, max_length=64, unique=True)),
                ('connection_name', models.CharField(help_text='Name for the Connection this install will create.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_oauth_connections', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
