# Generated by Django 5.2.17 on 2026-09-06 20:15

import django.core.validators
import integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='icon_image',
            field=models.FileField(blank=True, help_text="Optional uploaded logo (PNG/JPG/GIF/WEBP/SVG, up to 1MB); shown on the App Store card instead of the icon class above when set. A plain FileField rather than an ImageField — Pillow (which ImageField validates through) isn't a project dependency, and it can't decode SVG anyway.", null=True, upload_to='integrations/icons/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg']), integrations.models.validate_icon_image_size]),
        ),
        migrations.AlterField(
            model_name='integration',
            name='icon',
            field=models.CharField(default='bi-puzzle', help_text="A Bootstrap Icons class, e.g. 'bi-shop' — used as a fallback when no logo image is uploaded.", max_length=50),
        ),
    ]
