# Generated by Django 5.2.17 on 2026-09-07 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_auth_config_and_more'),
        ('integrations', '0002_integration_icon_image_alter_integration_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthpendingconnection',
            name='reconnect_connection',
            field=models.ForeignKey(blank=True, help_text='Set when this handshake is re-authorizing an existing App Store install rather than creating a new one — see integrations.views.reconnect_connection(). Re-using the same shared callback URL here (instead of a per-connection one) is what lets a provider registration with a single redirect URI work for both installing and reconnecting.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_reconnect_attempts', to='connections.connection'),
        ),
    ]
