# Generated by Django 5.2.17 on 2026-09-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_oauthpendingconnection_reconnect_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='is_file_based',
            field=models.BooleanField(default=False, help_text="This app has no real API behind it at all — installs skip Base URL/auth entirely, and each Connection's entities get their records from an uploaded CSV/XLSX file instead of an HTTP call (see schemas.discovery.read_all_records_from_source_file, used by jobs/engine.py). Used for the built-in CSV/XLSX apps."),
        ),
        migrations.AlterField(
            model_name='integration',
            name='category',
            field=models.CharField(choices=[('ECOMMERCE', 'E-commerce'), ('ERP', 'ERP'), ('ACCOUNTING', 'Accounting'), ('NOTIFICATIONS', 'Notifications'), ('CRM', 'CRM'), ('FILE', 'File'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20),
        ),
    ]
