# Generated by Django 5.2.17 on 2026-09-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_seed_file_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='oauth_client_auth',
            field=models.CharField(choices=[('body', 'Form fields (client_id / client_secret in the body)'), ('basic', 'HTTP Basic header (base64 of client_id:client_secret)')], default='body', help_text='How the token endpoint wants the client credentials: as form fields, or as an HTTP Basic header (Bling and many others). See connections/oauth.py.', max_length=10),
        ),
        migrations.AddField(
            model_name='integration',
            name='oauth_extra_headers',
            field=models.JSONField(blank=True, default=dict, help_text='{"header": "value"} sent on every token call and on every API request made with the token — e.g. {"enable-jwt": "1"} for Bling, which only issues JWT access tokens with it.'),
        ),
    ]
