# Generated by Django 5.2.17 on 2026-09-11 02:28

import django.core.validators
import django.db.models.deletion
import integrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, help_text='Personal profile photo (PNG/JPG/GIF/WEBP/SVG, up to 1MB).', null=True, upload_to='accounts/avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg']), integrations.models.validate_icon_image_size])),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_document', models.CharField(blank=True, help_text='Tax/registration id, e.g. CNPJ.', max_length=50)),
                ('company_icon', models.FileField(blank=True, help_text='Company logo, separate from the personal avatar above (up to 1MB).', null=True, upload_to='accounts/company_icons/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg']), integrations.models.validate_icon_image_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
