# Generated by Django 5.2.17 on 2026-09-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('records_read', models.IntegerField(default=0)),
                ('records_written', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('entity_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mappings.entitymapping')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='jobs.migrationrun')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('run', 'entity_mapping')},
            },
        ),
    ]
