# Generated by Django 5.2.17 on 2026-09-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_runstepstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrun',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Set when this run was scheduled for a future time instead of started immediately (see jobs/scheduler.py) — null for a run that started right away.', null=True),
        ),
        migrations.AlterField(
            model_name='migrationrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Set at creation time; for a scheduled run this is overwritten with the real start time once jobs/scheduler.py actually kicks it off.'),
        ),
    ]
