# Generated by Django 5.2.17 on 2026-09-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_migrationrun_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrun',
            name='rate_limit_per_second',
            field=models.FloatField(blank=True, help_text='Caps outbound requests/second (source reads and destination writes alike) — jobs/engine.py sleeps between calls to stay under it. Blank/null = unthrottled.', null=True),
        ),
    ]
