# Generated by Django 5.2.17 on 2026-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_migrationrun_rate_limit_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrun',
            name='input_file',
            field=models.FileField(blank=True, help_text="A CSV/XLSX uploaded just for this run, read instead of the mapping's source entity's own stored source_file — lets the same already-built mapping (fields, transforms, everything) run against fresh data each time without re-uploading through the connection's 'From file' discovery tab (which would also redo schema/field detection). Ignored for a source entity with no source_file at all (i.e. a real API source) — see jobs/engine.py::records_for.", null=True, upload_to='jobs/run_inputs/%Y/%m/'),
        ),
    ]
