# Generated by Django 5.2.17 on 2026-09-12 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_migrationrun_input_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrun',
            name='retry_of',
            field=models.ForeignKey(blank=True, help_text='Set when this run was created to retry failed entity mappings from a prior run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='jobs.migrationrun'),
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='retry_resolved',
            field=models.BooleanField(default=False, help_text='Set to True on the original failed run when one of its retries completes successfully.'),
        ),
    ]
