# Generated by Django 5.2.17 on 2026-09-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_retry_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrun',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Set by the Kill button. jobs/engine.py checks it between records and stops cleanly (status → cancelled); records already written stay written.'),
        ),
        migrations.AlterField(
            model_name='migrationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
