"""Builds the browser phrase files (static/js/i18n/<code>.js) from the source tables in i18n/sources/*.txt.

    python i18n/build.py            # from the datamigrator/ directory

Source format — one phrase per line, English first, then the seven translations, separated by " || ":

    en || pt-BR || es || fr || de || it || ja || zh

* Lines starting with # and blank lines are ignored.
* {1}, {2}… mark values filled in at runtime ("Page {1} of {2}"). Every translation must contain exactly the
  same tokens as the English, in any order — except a token glued to a word ("run{2}", a plural suffix), which may
  be dropped.
* If a phrase appears in several files the first one (files are read in name order) wins.

static/js/i18n.js loads only the file of the language in use and translates the page with it.
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "static" / "js" / "i18n"
LANGS = ["pt-BR", "es", "fr", "de", "it", "ja", "zh"]
TOKEN = re.compile(r"\{\d+\}")


def load_rows():
    """[(source_file, line_no, en, [7 translations])] in file order."""
    rows = []
    for path in sorted((HERE / "sources").glob("*.txt")):
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            cells = [c.strip() for c in line.split(" || ")]
            rows.append((path.name, n, cells))
    return rows


def required_tokens(en):
    """Tokens a translation must keep. A token glued to a word ("run{2}", the plural "s" of "1 run"/"3 runs")
    is only a suffix in English and may be left out — other languages plural differently."""
    return [t for t in TOKEN.findall(en) if not re.search(r"[A-Za-z]" + re.escape(t), en)]


def problems(rows):
    """Human-readable problems: wrong column count, empty cells, mismatching {n} tokens."""
    out = []
    for f, n, cells in rows:
        where = f"{f}:{n}"
        if len(cells) != 8:
            out.append(f"{where}: expected 8 columns, found {len(cells)} — {cells[0][:60]!r}")
            continue
        en = cells[0]
        for lang, tr in zip(LANGS, cells[1:]):
            if not tr:
                out.append(f"{where}: empty {lang} translation for {en[:60]!r}")
            elif sorted(TOKEN.findall(tr)) != sorted(required_tokens(en)) and sorted(TOKEN.findall(tr)) != sorted(TOKEN.findall(en)):
                out.append(f"{where}: {lang} tokens {TOKEN.findall(tr)} != {TOKEN.findall(en)} for {en[:60]!r}")
    return out


def tables(rows):
    """{lang: {english: translation}} — first occurrence wins."""
    result = {lang: {} for lang in LANGS}
    for _f, _n, cells in rows:
        if len(cells) != 8:
            continue
        for lang, tr in zip(LANGS, cells[1:]):
            result[lang].setdefault(cells[0], tr)
    return result


def build():
    rows = load_rows()
    bad = problems(rows)
    if bad:
        print("\n".join(bad[:60]))
        print(f"\n{len(bad)} problem(s) — nothing written.")
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    for lang, table in tables(rows).items():
        body = json.dumps(dict(sorted(table.items())), ensure_ascii=False, separators=(",", ":"))
        (OUT / f"{lang}.js").write_text(f"/* Generated by i18n/build.py — do not edit. */\nanteI18n.register({json.dumps(lang)},{body});\n", encoding="utf-8")
    print(f"{len(tables(rows)['pt-BR'])} phrases x {len(LANGS)} languages -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(build())
