import json
import pathlib
import shutil
import subprocess

from django.test import SimpleTestCase

from . import build

ROOT = pathlib.Path(__file__).resolve().parent
OUT = ROOT.parent / "static" / "js" / "i18n"


class SourceTests(SimpleTestCase):
    def test_every_row_is_complete_and_keeps_its_tokens(self):
        self.assertEqual(build.problems(build.load_rows()), [])

    def test_the_generated_language_files_match_the_sources(self):
        """Editing i18n/sources/*.txt without running `python i18n/build.py` leaves the browser on stale text."""
        tables = build.tables(build.load_rows())
        for lang, table in tables.items():
            body = json.dumps(dict(sorted(table.items())), ensure_ascii=False, separators=(",", ":"))
            expected = f"/* Generated by i18n/build.py — do not edit. */\nanteI18n.register({json.dumps(lang)},{body});\n"
            self.assertEqual((OUT / f"{lang}.js").read_text(encoding="utf-8"), expected, f"{lang}.js is out of date — run python i18n/build.py")

    def test_every_language_has_the_same_phrases(self):
        tables = build.tables(build.load_rows())
        keys = {lang: set(t) for lang, t in tables.items()}
        first = keys["pt-BR"]
        for lang, k in keys.items():
            self.assertEqual(k, first, lang)
        self.assertGreater(len(first), 1000)

    def test_translations_are_actually_translated(self):
        """A copied-over English value is only legitimate for names, acronyms and the like."""
        tables = build.tables(build.load_rows())
        for lang in ("ja", "zh"):
            same = [en for en, tr in tables[lang].items() if en == tr and len(en) > 25 and not en.startswith("http")]
            self.assertEqual(same, [], f"{lang}: long phrases left in English")


class EngineTests(SimpleTestCase):
    """The runtime translator (static/js/i18n.js) run under node with a stub DOM."""

    def run_engine(self, lang, inputs):
        if not shutil.which("node"):
            self.skipTest("node is not installed")
        result = subprocess.run(
            ["node", str(ROOT / "js_harness" / "engine_check.js"), lang, str(OUT / f"{lang}.js"), json.dumps(inputs)],
            capture_output=True, text=True, timeout=30)
        self.assertEqual(result.returncode, 0, result.stderr)
        return json.loads(result.stdout)

    def test_exact_phrases_keep_their_surrounding_whitespace(self):
        got = self.run_engine("pt-BR", ["Save changes", "  Cancel \n", "not a known phrase"])
        self.assertEqual(got, ["Salvar alterações", "  Cancelar \n", "not a known phrase"])

    def test_patterns_fill_in_values_and_can_reorder_them(self):
        self.assertEqual(self.run_engine("pt-BR", ["Page 3 of 9"]), ["Página 3 de 9"])
        self.assertEqual(self.run_engine("ja", ["Page 3 of 9"]), ["3 / 9 ページ"])

    def test_values_inside_a_pattern_are_translated_too(self):
        self.assertEqual(self.run_engine("es", ["Run #12 · Orders succeeded"]), ["Ejecución #12 · Orders completada con éxito"])
        got = self.run_engine("de", ["Plan “Nightly” was killed"])
        self.assertEqual(got, ["Plan „Nightly“ wurde beendet"])

    def test_plural_suffixes_and_empty_tails(self):
        got = self.run_engine("pt-BR", ["1 run selected", "3 runs selected", "Delete the department “Sales”?", "Delete the department “Sales”? 2 member(s) will simply be left without a department."])
        self.assertEqual(got[0], "1 execução(ões) selecionada(s)")
        self.assertEqual(got[1], "3 execução(ões) selecionada(s)")
        self.assertEqual(got[2], "Excluir o departamento “Sales”?")
        self.assertTrue(got[3].startswith("Excluir o departamento “Sales”?"))

    def test_a_list_of_modules_in_a_permission_message(self):
        got = self.run_engine("es", ["You don't have permission to use Mappings or Studio. Ask an administrator to enable it for your account."])
        self.assertEqual(got, ["No tienes permiso para usar Mapeos o Studio. Pide a un administrador que lo active para tu cuenta."])

    def test_english_needs_no_phrase_file_and_is_untouched(self):
        # Under lang=en nothing is registered, so every string comes back as it went in.
        got = self.run_engine("en", ["Save changes"]) if (OUT / "en.js").exists() else None
        self.assertIsNone(got)
        self.assertFalse((OUT / "en.js").exists())
