# Generated by Django 5.2.17 on 2026-09-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], max_length=12)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'name', '-created_at'], name='home_status_group_27b83e_idx')],
            },
        ),
    ]
