# Generated by Django 5.2.17 on 2026-09-11 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0002_entity_source_file_alter_entity_endpoint_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('field_ids', models.JSONField(blank=True, default=list, help_text="This entity's selected columns, in the order they'll appear in the CSV/preview — a plain list of schemas.Field ids (validated against the section's own entity in reports/views.py, not enforced at the DB level).")),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schemas.entity')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('report', 'order')},
            },
        ),
    ]
