# Generated by Django 5.2.17 on 2026-09-07 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0004_apicalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(help_text="Every step in this chain calls this connection's API, using its configured auth.", on_delete=django.db.models.deletion.CASCADE, related_name='call_chains', to='connections.connection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallChainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, help_text="Every step's parsed JSON response, keyed by step name — this is exactly what later steps' {{name.path}} placeholders are resolved against (see chains/executor.py), saved to a real file so it can be read back afterward for the same purpose.", null=True, upload_to='chains/results/%Y/%m/')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='chains.callchain')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Referenced by later steps as {{this_name.some.json.path}} — must be unique within the chain.')),
                ('order', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('path', models.CharField(help_text="Endpoint path, relative to the chain's connection base_url. May reference a prior step's response with {{step_name.field.path}}, e.g. /orders/{{create_customer.id}}.", max_length=500)),
                ('body', models.TextField(blank=True, help_text='Optional JSON request body template. {{step_name.field.path}} placeholders are replaced with the referenced value (as real JSON — a number stays a number), then the whole thing is parsed as JSON, e.g. {"customer_id": {{create_customer.id}}}.')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chains.callchain')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chain', 'name'), ('chain', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CallChainStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('resolved_path', models.CharField(blank=True, max_length=500)),
                ('resolved_body', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='chains.callchainrun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chains.callchainstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
