# Generated by Django 5.2.17 on 2026-09-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callchainstep',
            name='captures',
            field=models.JSONField(blank=True, default=list, help_text='Named values pulled out of THIS step\'s response for later steps to reference by a short name instead of the full {{this_name.some.json.path}} — a list of {"name": "customer_id", "path": "id"} objects (path may be blank to capture the whole response). Once captured, {{customer_id}} works anywhere {{create_customer.id}} would (see chains/executor.py::apply_captures) — same context dict either way.'),
        ),
        migrations.AddField(
            model_name='callchainstepresult',
            name='captured_variables',
            field=models.JSONField(blank=True, default=dict, help_text='{variable_name: extracted_value} for every capture defined on this step, as it actually resolved on this run.'),
        ),
    ]
