# Generated by Django 5.2.17 on 2026-09-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0002_callchainstep_captures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callchainstep',
            name='async_condition_path',
            field=models.CharField(blank=True, help_text='Dotted path into the poll response checked after every poll, e.g. status or data.state.', max_length=200),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='async_condition_value',
            field=models.CharField(blank=True, help_text="Polling stops once async_condition_path's value equals this (case-insensitive string compare), e.g. completed.", max_length=200),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='async_interval_seconds',
            field=models.FloatField(default=2.0, help_text='Wait between polls.'),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='async_poll_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='async_poll_path',
            field=models.CharField(blank=True, help_text="Status-check endpoint, relative to the connection's base_url. May reference this step's own submit response, e.g. /exports/{{this_name.job_id}}/status.", max_length=500),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='async_result_path',
            field=models.CharField(blank=True, help_text="Optional: one more GET once the condition is met, e.g. /exports/{{this_name.job_id}}/download — its response becomes this step's result instead of the last poll response. Leave blank to just use the last poll response.", max_length=500),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='async_timeout_seconds',
            field=models.FloatField(default=60.0, help_text='Give up (fail this step) after this long.'),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='is_async',
            field=models.BooleanField(default=False, help_text="This step's own request only starts a job on the external API (a common pattern for bulk/report/export endpoints) — after it responds, poll async_poll_path until async_condition_path in the poll response equals async_condition_value, then (optionally) fetch async_result_path once. Whatever comes back last is what this step's captures/{{name.path}} references end up seeing, exactly as if it had been the immediate response — see chains/executor.py::run_async_step."),
        ),
        migrations.AddField(
            model_name='callchainstepresult',
            name='poll_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Set for an async step only — how many times it polled before completing.', null=True),
        ),
    ]
