# Generated by Django 5.2.17 on 2026-09-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0004_alter_callchainstep_captures'),
    ]

    operations = [
        migrations.AddField(
            model_name='callchainstep',
            name='kind',
            field=models.CharField(choices=[('http', 'HTTP call'), ('wait', 'Wait'), ('next', 'Next page'), ('find', 'Find in list'), ('check', 'Check header'), ('file', 'File preview')], default='http', help_text='What this step does. HTTP calls are the original (and default) kind; the others work on data earlier steps already fetched, or just pause — see chains/executor.py.', max_length=10),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Settings for the non-HTTP kinds (wait: seconds · next: from_step/next_path/items_path/cursor_param/max_pages · find: source/match_field/operator/value/pick/on_missing · check: from_step/header/operator/value/on_fail · file: entity/limit). Validated in chains/views.py::parse_kind_params.'),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='timeout_seconds',
            field=models.FloatField(blank=True, help_text="HTTP steps only: give up on the request after this many seconds (blank = the connection client's default, 30s). Also applies to an async step's poll/result calls.", null=True),
        ),
        migrations.AddField(
            model_name='callchainstepresult',
            name='detail',
            field=models.JSONField(blank=True, default=dict, help_text="What a non-HTTP step found/decided, for the run detail view — e.g. a check's expected vs actual header, a find's match count, a file preview's rows."),
        ),
        migrations.AddField(
            model_name='callchainstepresult',
            name='kind',
            field=models.CharField(default='http', max_length=10),
        ),
        migrations.AddField(
            model_name='callchainstepresult',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict, help_text="The HTTP response's headers (names as sent), kept so a later 'check header' step — or a retried run — can read them."),
        ),
        migrations.AlterField(
            model_name='callchainstep',
            name='path',
            field=models.CharField(blank=True, help_text="Endpoint path, relative to the chain's connection base_url. May reference a prior step's response with {{step_name.field.path}}, e.g. /orders/{{create_customer.id}}.", max_length=500),
        ),
    ]
