# Generated by Django 5.2.17 on 2026-09-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0005_step_kinds'),
        ('connections', '0006_connection_rate_limit_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='callchain',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Owned by a plan: holds the function blocks (request, find, check…) dragged into a custom run so they can share data. Never listed as a chain of its own.'),
        ),
        migrations.AddField(
            model_name='callchainrun',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Set by the Kill button; the runner checks it between steps, while waiting and while polling.'),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='connection',
            field=models.ForeignKey(blank=True, help_text="Overrides the chain's connection for this one step — a plan's custom run has no single connection, so each of its request steps names its own.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='callchainrun',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled')], max_length=10),
        ),
    ]
