# Generated by Django 5.2.17 on 2026-09-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0006_cancel_and_inline'),
    ]

    operations = [
        migrations.AddField(
            model_name='callchainstep',
            name='headers',
            field=models.JSONField(blank=True, default=list, help_text="HTTP steps only: extra request headers, a list of {name, value}. Values may use {{placeholders}}. They override the connection's own headers of the same name, and are also sent on an async step's poll/result calls and on the pages a next-page step fetches."),
        ),
        migrations.AddField(
            model_name='callchainstep',
            name='query_params',
            field=models.JSONField(blank=True, default=list, help_text='HTTP steps only: query string parameters, a list of {name, value} (values may use {{placeholders}}). A next-page step repeats them on every page.'),
        ),
    ]
