# Generated by Django 5.2.17 on 2026-09-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_connections', models.ManyToManyField(blank=True, help_text='The integration destinies. Add more than one to fan the same source out to several systems.', related_name='mappings_as_destination', to='connections.connection')),
                ('source_connection', models.ForeignKey(help_text='The integration origin.', on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_source', to='connections.connection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schemas.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schemas.entity')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mappings', to='mappings.mapping')),
            ],
            options={
                'unique_together': {('mapping', 'source_entity', 'target_entity')},
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform', models.CharField(blank=True, help_text='Optional Python expression applied to `value` before writing, e.g. value.upper() or value[:10]', max_length=255)),
                ('entity_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='mappings.entitymapping')),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schemas.field')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schemas.field')),
            ],
            options={
                'unique_together': {('entity_mapping', 'source_field', 'target_field')},
            },
        ),
    ]
