# Generated by Django 5.2.17 on 2026-09-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymapping',
            name='write_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', help_text="HTTP verb used to write each mapped record to the target entity's endpoint_path (jobs/engine.py).", max_length=10),
        ),
    ]
