# Generated by Django 5.2.17 on 2026-09-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0002_entitymapping_write_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='transform_rules',
            field=models.JSONField(blank=True, default=list, help_text='No-code transform steps applied in order before writing (uppercase/lowercase/trim, map specific values, default-if-empty) — see jobs/engine.py::_apply_rules for the exact rule shapes. The friendly alternative to writing a raw `transform` expression; applied first, then `transform` runs on the result if also set.'),
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='transform',
            field=models.CharField(blank=True, help_text="Advanced/optional: a Python expression applied to `value` after transform_rules, e.g. value.upper() or value[:10] — for anything the no-code rules above can't express.", max_length=255),
        ),
    ]
