# Generated by Django 5.2.17 on 2026-09-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_fieldmapping_transform_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='match_reason',
            field=models.CharField(blank=True, help_text='Why auto-mapping suggested this wire.', max_length=200),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='match_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Auto-mapping's confidence, 0-100.", null=True),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('draft', 'Draft')], default='confirmed', max_length=10),
        ),
    ]
