# Generated by Django 5.2.17 on 2026-09-12 04:22

from django.db import migrations
from django.utils import timezone


def backfill_resolved_at(apps, schema_editor):
    Incident = apps.get_model('incidents', 'Incident')
    Incident.objects.filter(status='resolved', resolved_at__isnull=True).update(resolved_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_acknowledged_at_incident_affected_services_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_resolved_at, migrations.RunPython.noop),
    ]
