# Generated by Django 5.2.17 on 2026-09-10 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0002_callchainstep_captures_and_more'),
        ('mappings', '0003_fieldmapping_transform_rules_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationplan',
            name='execution_mode',
            field=models.CharField(choices=[('simple', 'Simple execution — sequential mapping runs'), ('chain', 'Chain mode — sequential chain executions')], default='simple', help_text="Chosen once at creation and fixed afterward — decides whether this plan's steps are Mappings (simple) or Chains (chain mode).", max_length=10),
        ),
        migrations.AddField(
            model_name='planstep',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chains.callchain'),
        ),
        migrations.AddField(
            model_name='planstep',
            name='chain_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chains.callchainrun'),
        ),
        migrations.AlterField(
            model_name='migrationplan',
            name='rate_limit_per_second',
            field=models.FloatField(blank=True, help_text="Default requests/second cap applied to every simple-mode step's run — a step can override this. Unused in chain mode (chains have no rate limiting of their own).", null=True),
        ),
        migrations.AlterField(
            model_name='planstep',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mappings.mapping'),
        ),
        migrations.AlterField(
            model_name='planstep',
            name='rate_limit_per_second',
            field=models.FloatField(blank=True, help_text="Overrides the plan's rate limit for this step only (simple mode only).", null=True),
        ),
    ]
