# Generated by Django 5.2.17 on 2026-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_migrationplan_execution_mode_planstep_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationplan',
            name='execution_mode',
            field=models.CharField(choices=[('simple', 'Simple execution — sequential mapping runs'), ('chain', 'Chain mode — sequential chain executions'), ('mixed', 'Mixed — mappings and chains in one sequence')], default='simple', help_text="Chosen once at creation and fixed afterward — decides whether this plan's steps are Mappings (simple), Chains (chain mode), or either, freely mixed (mixed).", max_length=10),
        ),
    ]
