# Generated by Django 5.2.17 on 2026-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_mixed_execution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstep',
            name='entity_mapping_ids',
            field=models.JSONField(blank=True, default=list, help_text="Mapping steps only: run just these entity pairs (ids of the mapping's EntityMappings). Empty = the whole mapping."),
        ),
        migrations.AddField(
            model_name='planstep',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Set for a wait step once it has waited.', null=True),
        ),
        migrations.AddField(
            model_name='planstep',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Set for a wait step while it pauses.', null=True),
        ),
        migrations.AddField(
            model_name='planstep',
            name='wait_seconds',
            field=models.FloatField(blank=True, help_text='Makes this a pause step: no mapping or chain, just wait this long before the next step.', null=True),
        ),
    ]
