# Generated by Django 5.2.17 on 2026-09-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0006_cancel_and_inline'),
        ('plans', '0004_step_wait_and_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationplan',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Set by the Kill button; plans/executor.py stops before the next step (and mid-wait).'),
        ),
        migrations.AddField(
            model_name='migrationplan',
            name='inline_chain',
            field=models.ForeignKey(blank=True, help_text="Hidden chain holding this plan's function steps (request, find, check, file…), so they can pass data to one another during a run.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chains.callchain'),
        ),
        migrations.AddField(
            model_name='migrationplan',
            name='inline_run',
            field=models.ForeignKey(blank=True, help_text="The single chain run all of the plan's function steps recorded their results on, this execution.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chains.callchainrun'),
        ),
        migrations.AddField(
            model_name='planstep',
            name='inline_step',
            field=models.ForeignKey(blank=True, help_text="A function step (request, find in list, check header, next page, file preview…) that lives in the plan's hidden inline chain.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chains.callchainstep'),
        ),
        migrations.AlterField(
            model_name='migrationplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
