# Generated by Django 5.2.17 on 2026-09-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('endpoint_path', models.CharField(blank=True, help_text="Path used to read/write records, relative to the connection's base URL, e.g. /customers", max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('openapi', 'OpenAPI import'), ('sampled', 'Sampled from response')], default='manual', max_length=20)),
                ('canvas_x', models.IntegerField(default=40)),
                ('canvas_y', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='connections.connection')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['name'],
                'unique_together': {('connection', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('number', 'number'), ('integer', 'integer'), ('boolean', 'boolean'), ('object', 'object'), ('array', 'array'), ('date', 'date')], default='string', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('sample_value', models.CharField(blank=True, max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='schemas.entity')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('entity', 'name')},
            },
        ),
    ]
