# Generated by Django 5.2.17 on 2026-09-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='source_file',
            field=models.FileField(blank=True, help_text="A CSV or .xlsx file this entity's records come from directly — jobs/engine.py reads every row from here instead of making an HTTP request, so a mapping can use this entity as its source with no real API/connection behind it at all (see connections/detail.html's 'From file' discovery tab, which sets this and tags source='manual').", null=True, upload_to='schemas/source_files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='endpoint_path',
            field=models.CharField(blank=True, help_text="Path used to read/write records, relative to the connection's base URL, e.g. /customers. Unused when source_file is set — records come from the file instead of an HTTP call.", max_length=255),
        ),
    ]
